[package]
name = "rhythm_engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rubato.workspace = true
symphonia.workspace = true
cpal.workspace = true
wgpu.workspace = true
image.workspace = true
rhythm_core = { path = "../rhythm_core" }

[lints]
workspace = true
