@echo off
setlocal EnableExtensions
cd /d "%~dp0"

set "OUT=docs\06-quality\baselines\LOCAL_WINDOWS.md"
if not exist "docs\06-quality\baselines" mkdir "docs\06-quality\baselines"

echo Measuring Rhythm Effects build baseline on this machine...
echo This intentionally performs clean builds and can take a while.
echo.

powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ErrorActionPreference='Stop';" ^
  "$repo=(Get-Location).Path;" ^
  "$cpu=(Get-CimInstance Win32_Processor | Select-Object -First 1 -ExpandProperty Name).Trim();" ^
  "$ram=[math]::Round((Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory/1GB,1);" ^
  "$os=(Get-CimInstance Win32_OperatingSystem);" ^
  "$rust=(rustc --version);" ^
  "$cargo=(cargo --version);" ^
  "function Measure-Cmd([string]$cmd) { $sw=[Diagnostics.Stopwatch]::StartNew(); cmd /c $cmd | Out-Host; if($LASTEXITCODE -ne 0){throw ('Command failed: '+$cmd)}; $sw.Stop(); [math]::Round($sw.Elapsed.TotalSeconds,2) };" ^
  "cargo clean | Out-Host;" ^
  "$debug=Measure-Cmd 'cargo build --workspace';" ^
  "cargo clean | Out-Host;" ^
  "$release=Measure-Cmd 'cargo build --workspace --release';" ^
  "$tests=Measure-Cmd 'cargo test --workspace';" ^
  "$appFile=Join-Path $repo 'crates\rhythm_app\src\main.rs';" ^
  "$old=[IO.File]::GetLastWriteTimeUtc($appFile); [IO.File]::SetLastWriteTimeUtc($appFile,[DateTime]::UtcNow);" ^
  "$appInc=Measure-Cmd 'cargo build -p rhythm_app'; [IO.File]::SetLastWriteTimeUtc($appFile,$old);" ^
  "$coreFile=Join-Path $repo 'crates\rhythm_core\src\lib.rs';" ^
  "$oldCore=[IO.File]::GetLastWriteTimeUtc($coreFile); [IO.File]::SetLastWriteTimeUtc($coreFile,[DateTime]::UtcNow);" ^
  "$coreInc=Measure-Cmd 'cargo build -p rhythm_app'; [IO.File]::SetLastWriteTimeUtc($coreFile,$oldCore);" ^
  "$date=(Get-Date).ToString('yyyy-MM-dd HH:mm:ss zzz');" ^
  "$lines=@('# Local Windows Build Baseline','','Generated by measure_build_baseline.bat.','', ('- Date: '+$date), ('- OS: '+$os.Caption+' '+$os.Version), ('- CPU: '+$cpu), ('- RAM: '+$ram+' GiB'), ('- Rust: '+$rust), ('- Cargo: '+$cargo),'','## Measurements','','| Measurement | Seconds |','|---|---:|',('| Clean debug workspace build | '+$debug+' |'),('| Clean release workspace build | '+$release+' |'),('| Workspace tests | '+$tests+' |'),('| Incremental rhythm_app touch/build | '+$appInc+' |'),('| Incremental rhythm_core touch -> rhythm_app build | '+$coreInc+' |'),'','These values are the initial local reference-machine baseline used by PERFORMANCE.md regression policy.');" ^
  "[IO.File]::WriteAllLines((Join-Path $repo $env:OUT),$lines,[Text.UTF8Encoding]::new($false));" ^
  "Write-Host ''; Write-Host ('Wrote '+$env:OUT)"

if errorlevel 1 (
  echo.
  echo [ERROR] Baseline measurement failed.
  pause
  exit /b 1
)

echo.
echo Baseline written to %OUT%
echo Commit this file when convenient.
pause